name: MyAnimeList
description: This adapter was designed to allow the consumer to request a type of anime (movie, tv show, airing) and ranking (1 , 2 , 3....) to query the top 500 anime of that type and return the animeId of the anime at that rank.

node_identifier: N/A

platforms:
  - Docker

data_sources:
  - name: MyAnimeList
    url: https://myanimelist.net/

parameters:
  - ranking_type
  - rank
