name: MyAnimeList
description: Request a type of anime and ranking to query the top 500 anime of that type and return the animeId of the anime at that rank.

node_identifier: MAL

platforms:
  - Docker

data_sources:
  - name: MyAnimeList
    url: https://api.myanimelist.net/v2/anime/ranking

parameters:
  - ranking_type
  - rank
